/* Generated by F* Custard extraction. Do not edit. */
#ifndef __CUSTARD_H
#define __CUSTARD_H

#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct Data_Codec_Spike_decode_res_s Data_Codec_Spike_decode_res;

enum Data_Codec_Spike_decode_res_tags {
  DATA_CODEC_SPIKE_DR_OK,
  DATA_CODEC_SPIKE_DR_EOF
};
struct Data_Codec_Spike_decode_res_s {
  enum Data_Codec_Spike_decode_res_tags tag;
  union {
    struct {
      uint32_t _0;
      uint32_t _1;
    } Dr_ok;
    uint32_t Dr_eof;
  } val;
};

uint32_t Data_Codec_Spike_encode_token(uint32_t v, uint8_t *b, uint32_t i);
Data_Codec_Spike_decode_res Data_Codec_Spike_decode_token(uint8_t *b, uint32_t i, uint32_t n);


#ifdef __cplusplus
}
#endif
#endif

