/* Generated by F* Custard extraction. Do not edit. */
#include "Custard.h"

uint32_t Data_Codec_Spike_encode_token(uint32_t v, uint8_t *b, uint32_t i) {
  uint8_t x = (uint8_t)v;
  size_t j = (size_t)i;
  b[j] = x;
  return 1;
}

Data_Codec_Spike_decode_res Data_Codec_Spike_decode_token(uint8_t *b, uint32_t i, uint32_t n) {
  if (i < (i + n)) {
    size_t j = (size_t)i;
    uint8_t x = b[j];
    return (Data_Codec_Spike_decode_res){ .tag = DATA_CODEC_SPIKE_DR_OK, .val = { .Dr_ok = { ._0 = 1, ._1 = (uint32_t)x } } };
  }
  else return (Data_Codec_Spike_decode_res){ .tag = DATA_CODEC_SPIKE_DR_EOF, .val = { .Dr_eof = i } };
}


