/* Generated by F* Custard extraction. Do not edit. */
#include "Custard.h"

uint32_t Data_Codec_Low_encode_token(uint32_t v, uint8_t *b, uint32_t i) {
  uint8_t x = (uint8_t)v;
  size_t j = (size_t)i;
  b[j] = x;
  return 1;
}

uint32_t Data_Codec_Low_encode_byteval(uint8_t x, uint8_t *b, uint32_t i) {
  size_t j = (size_t)i;
  b[j] = x;
  return 1;
}

uint32_t Data_Codec_Low_encode_uint8(uint32_t v, uint8_t *b, uint32_t i) {
  uint8_t x = (uint8_t)v;
  size_t j = (size_t)i;
  b[j] = x;
  return 1;
}

uint32_t Data_Codec_Low_encode_word16be(uint32_t v, uint8_t *b, uint32_t i) {
  uint8_t hi = (uint8_t)(v / 256);
  uint8_t lo = (uint8_t)(v % 256);
  size_t j = (size_t)i;
  size_t j1 = (size_t)(i + 1);
  b[j] = hi;
  b[j1] = lo;
  return 2;
}

uint32_t Data_Codec_Low_encode_word32be(uint32_t v, uint8_t *b, uint32_t i) {
  uint8_t b0 = (uint8_t)(v / 16777216U);
  uint8_t b1 = (uint8_t)((v / 65536U) % 256);
  uint8_t b2 = (uint8_t)((v / 256) % 256);
  uint8_t b3 = (uint8_t)(v % 256);
  size_t j = (size_t)i;
  size_t j1 = (size_t)(i + 1);
  size_t j2 = (size_t)(i + 2);
  size_t j3 = (size_t)(i + 3);
  b[j] = b0;
  b[j1] = b1;
  b[j2] = b2;
  b[j3] = b3;
  return 4;
}

uint32_t Data_Codec_Low_encode_word16le(uint32_t v, uint8_t *b, uint32_t i) {
  uint8_t lo = (uint8_t)(v % 256);
  uint8_t hi = (uint8_t)(v / 256);
  size_t j = (size_t)i;
  size_t j1 = (size_t)(i + 1);
  b[j] = lo;
  b[j1] = hi;
  return 2;
}

uint32_t Data_Codec_Low_encode_word32le(uint32_t v, uint8_t *b, uint32_t i) {
  uint8_t b0 = (uint8_t)(v % 256);
  uint8_t b1 = (uint8_t)((v / 256) % 256);
  uint8_t b2 = (uint8_t)((v / 65536U) % 256);
  uint8_t b3 = (uint8_t)(v / 16777216U);
  size_t j = (size_t)i;
  size_t j1 = (size_t)(i + 1);
  size_t j2 = (size_t)(i + 2);
  size_t j3 = (size_t)(i + 3);
  b[j] = b0;
  b[j1] = b1;
  b[j2] = b2;
  b[j3] = b3;
  return 4;
}

uint32_t Data_Codec_Low_encode_varint(uint32_t v, uint8_t *b, uint32_t i) {
  if (v < 128) {
    size_t j = (size_t)i;
    uint8_t x = (uint8_t)v;
    b[j] = x;
    return 1;
  }
  else {
    if (v < 16384) {
      size_t j0 = (size_t)i;
      size_t j1 = (size_t)(i + 1);
      uint8_t x0 = (uint8_t)((v % 128) + 128);
      uint8_t x1 = (uint8_t)(v / 128);
      b[j0] = x0;
      b[j1] = x1;
      return 2;
    }
    else {
      if (v < 2097152U) {
        size_t j0_1 = (size_t)i;
        size_t j1_1 = (size_t)(i + 1);
        size_t j2 = (size_t)(i + 2);
        uint8_t x0_1 = (uint8_t)((v % 128) + 128);
        uint8_t x1_1 = (uint8_t)(((v / 128) % 128) + 128);
        uint8_t x2 = (uint8_t)(v / 16384);
        b[j0_1] = x0_1;
        b[j1_1] = x1_1;
        b[j2] = x2;
        return 3;
      }
      else {
        if (v < 268435456U) {
          size_t j0_2 = (size_t)i;
          size_t j1_2 = (size_t)(i + 1);
          size_t j2_1 = (size_t)(i + 2);
          size_t j3 = (size_t)(i + 3);
          uint8_t x0_2 = (uint8_t)((v % 128) + 128);
          uint8_t x1_2 = (uint8_t)(((v / 128) % 128) + 128);
          uint8_t x2_1 = (uint8_t)(((v / 16384) % 128) + 128);
          uint8_t x3 = (uint8_t)(v / 2097152U);
          b[j0_2] = x0_2;
          b[j1_2] = x1_2;
          b[j2_1] = x2_1;
          b[j3] = x3;
          return 4;
        }
        else {
          size_t j0_3 = (size_t)i;
          size_t j1_3 = (size_t)(i + 1);
          size_t j2_2 = (size_t)(i + 2);
          size_t j3_1 = (size_t)(i + 3);
          size_t j4 = (size_t)(i + 4);
          uint8_t x0_3 = (uint8_t)((v % 128) + 128);
          uint8_t x1_3 = (uint8_t)(((v / 128) % 128) + 128);
          uint8_t x2_2 = (uint8_t)(((v / 16384) % 128) + 128);
          uint8_t x3_1 = (uint8_t)(((v / 2097152U) % 128) + 128);
          uint8_t x4 = (uint8_t)(v / 268435456U);
          b[j0_3] = x0_3;
          b[j1_3] = x1_3;
          b[j2_2] = x2_2;
          b[j3_1] = x3_1;
          b[j4] = x4;
          return 5;
        }
      }
    }
  }
}

Data_Codec_Low_decode_result_c Data_Codec_Low_decode_token(uint8_t *b, uint32_t i, uint32_t n) {
  if (i < (i + n)) {
    size_t j = (size_t)i;
    uint8_t x = b[j];
    return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INR, .val = { .DR_Inr = (Data_Codec_Low_decode_result_ok){ .n = 1, .value = (uint32_t)x } } };
  }
  else return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INL, .val = { .DR_Inl = (Data_Codec_Low_decode_error_c){ .code = (Data_Codec_Low_error_code_c){ .tag = DATA_CODEC_LOW_EC_UNEXPECTEDENDOFINPUT }, .pos = i } } };
}

Data_Codec_Low_decode_result_c Data_Codec_Low_decode_byteval(uint8_t x, uint8_t *b, uint32_t i, uint32_t n) {
  if (i < (i + n)) {
    size_t j = (size_t)i;
    uint8_t y = b[j];
    if (y == x) return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INR, .val = { .DR_Inr = (Data_Codec_Low_decode_result_ok){ .n = 1, .value = 0 } } };
    else return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INL, .val = { .DR_Inl = (Data_Codec_Low_decode_error_c){ .code = (Data_Codec_Low_error_code_c){ .tag = DATA_CODEC_LOW_EC_EXPECTEDBYTE, .val = { .EC_ExpectedByte = y } }, .pos = i } } };
  }
  else return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INL, .val = { .DR_Inl = (Data_Codec_Low_decode_error_c){ .code = (Data_Codec_Low_error_code_c){ .tag = DATA_CODEC_LOW_EC_UNEXPECTEDENDOFINPUT }, .pos = i } } };
}

Data_Codec_Low_decode_result_c Data_Codec_Low_decode_uint8(uint8_t *b, uint32_t i, uint32_t n) {
  if (i < (i + n)) {
    size_t j = (size_t)i;
    uint8_t x = b[j];
    return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INR, .val = { .DR_Inr = (Data_Codec_Low_decode_result_ok){ .n = 1, .value = (uint32_t)x } } };
  }
  else return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INL, .val = { .DR_Inl = (Data_Codec_Low_decode_error_c){ .code = (Data_Codec_Low_error_code_c){ .tag = DATA_CODEC_LOW_EC_UNEXPECTEDENDOFINPUT }, .pos = i } } };
}

Data_Codec_Low_decode_result_c Data_Codec_Low_decode_word16be(uint8_t *b, uint32_t i, uint32_t n) {
  if ((i + 2) <= (i + n)) {
    size_t j0 = (size_t)i;
    size_t j1 = (size_t)(i + 1);
    uint8_t hi = b[j0];
    uint8_t lo = b[j1];
    uint32_t value = (((uint32_t)hi * 256) + (uint32_t)lo);
    return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INR, .val = { .DR_Inr = (Data_Codec_Low_decode_result_ok){ .n = 2, .value = value } } };
  }
  else return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INL, .val = { .DR_Inl = (Data_Codec_Low_decode_error_c){ .code = (Data_Codec_Low_error_code_c){ .tag = DATA_CODEC_LOW_EC_UNEXPECTEDENDOFINPUT }, .pos = i } } };
}

Data_Codec_Low_decode_result_c Data_Codec_Low_decode_word32be(uint8_t *b, uint32_t i, uint32_t n) {
  if ((i + 4) <= (i + n)) {
    size_t j0 = (size_t)i;
    size_t j1 = (size_t)(i + 1);
    size_t j2 = (size_t)(i + 2);
    size_t j3 = (size_t)(i + 3);
    uint8_t b0 = b[j0];
    uint8_t b1 = b[j1];
    uint8_t b2 = b[j2];
    uint8_t b3 = b[j3];
    uint32_t value = (((((uint32_t)b0 * 16777216U) + ((uint32_t)b1 * 65536U)) + ((uint32_t)b2 * 256)) + (uint32_t)b3);
    return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INR, .val = { .DR_Inr = (Data_Codec_Low_decode_result_ok){ .n = 4, .value = value } } };
  }
  else return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INL, .val = { .DR_Inl = (Data_Codec_Low_decode_error_c){ .code = (Data_Codec_Low_error_code_c){ .tag = DATA_CODEC_LOW_EC_UNEXPECTEDENDOFINPUT }, .pos = i } } };
}

Data_Codec_Low_decode_result_c Data_Codec_Low_decode_word16le(uint8_t *b, uint32_t i, uint32_t n) {
  if ((i + 2) <= (i + n)) {
    size_t j0 = (size_t)i;
    size_t j1 = (size_t)(i + 1);
    uint8_t lo = b[j0];
    uint8_t hi = b[j1];
    uint32_t value = ((uint32_t)lo + ((uint32_t)hi * 256));
    return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INR, .val = { .DR_Inr = (Data_Codec_Low_decode_result_ok){ .n = 2, .value = value } } };
  }
  else return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INL, .val = { .DR_Inl = (Data_Codec_Low_decode_error_c){ .code = (Data_Codec_Low_error_code_c){ .tag = DATA_CODEC_LOW_EC_UNEXPECTEDENDOFINPUT }, .pos = i } } };
}

Data_Codec_Low_decode_result_c Data_Codec_Low_decode_word32le(uint8_t *b, uint32_t i, uint32_t n) {
  if ((i + 4) <= (i + n)) {
    size_t j0 = (size_t)i;
    size_t j1 = (size_t)(i + 1);
    size_t j2 = (size_t)(i + 2);
    size_t j3 = (size_t)(i + 3);
    uint8_t b0 = b[j0];
    uint8_t b1 = b[j1];
    uint8_t b2 = b[j2];
    uint8_t b3 = b[j3];
    uint32_t value = ((((uint32_t)b0 + ((uint32_t)b1 * 256)) + ((uint32_t)b2 * 65536U)) + ((uint32_t)b3 * 16777216U));
    return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INR, .val = { .DR_Inr = (Data_Codec_Low_decode_result_ok){ .n = 4, .value = value } } };
  }
  else return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INL, .val = { .DR_Inl = (Data_Codec_Low_decode_error_c){ .code = (Data_Codec_Low_error_code_c){ .tag = DATA_CODEC_LOW_EC_UNEXPECTEDENDOFINPUT }, .pos = i } } };
}

Data_Codec_Low_decode_result_c Data_Codec_Low_decode_varint(uint8_t *b, uint32_t i, uint32_t n) {
  if (n < 1) return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INL, .val = { .DR_Inl = (Data_Codec_Low_decode_error_c){ .code = (Data_Codec_Low_error_code_c){ .tag = DATA_CODEC_LOW_EC_UNEXPECTEDENDOFINPUT }, .pos = i } } };
  else {
    size_t j0 = (size_t)i;
    uint8_t b0 = b[j0];
    uint32_t v0 = ((uint32_t)b0 % 128);
    if (b0 < 128) return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INR, .val = { .DR_Inr = (Data_Codec_Low_decode_result_ok){ .n = 1, .value = v0 } } };
    else {
      if (n < 2) return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INL, .val = { .DR_Inl = (Data_Codec_Low_decode_error_c){ .code = (Data_Codec_Low_error_code_c){ .tag = DATA_CODEC_LOW_EC_UNEXPECTEDENDOFINPUT }, .pos = i } } };
      else {
        size_t j1 = (size_t)(i + 1);
        uint8_t b1 = b[j1];
        uint32_t v1 = (v0 + (((uint32_t)b1 % 128) * 128));
        if (b1 < 128) return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INR, .val = { .DR_Inr = (Data_Codec_Low_decode_result_ok){ .n = 2, .value = v1 } } };
        else {
          if (n < 3) return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INL, .val = { .DR_Inl = (Data_Codec_Low_decode_error_c){ .code = (Data_Codec_Low_error_code_c){ .tag = DATA_CODEC_LOW_EC_UNEXPECTEDENDOFINPUT }, .pos = i } } };
          else {
            size_t j2 = (size_t)(i + 2);
            uint8_t b2 = b[j2];
            uint32_t v2 = (v1 + (((uint32_t)b2 % 128) * 16384));
            if (b2 < 128) return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INR, .val = { .DR_Inr = (Data_Codec_Low_decode_result_ok){ .n = 3, .value = v2 } } };
            else {
              if (n < 4) return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INL, .val = { .DR_Inl = (Data_Codec_Low_decode_error_c){ .code = (Data_Codec_Low_error_code_c){ .tag = DATA_CODEC_LOW_EC_UNEXPECTEDENDOFINPUT }, .pos = i } } };
              else {
                size_t j3 = (size_t)(i + 3);
                uint8_t b3 = b[j3];
                uint32_t v3 = (v2 + (((uint32_t)b3 % 128) * 2097152U));
                if (b3 < 128) return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INR, .val = { .DR_Inr = (Data_Codec_Low_decode_result_ok){ .n = 4, .value = v3 } } };
                else {
                  if (n < 5) return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INL, .val = { .DR_Inl = (Data_Codec_Low_decode_error_c){ .code = (Data_Codec_Low_error_code_c){ .tag = DATA_CODEC_LOW_EC_UNEXPECTEDENDOFINPUT }, .pos = i } } };
                  else {
                    size_t j4 = (size_t)(i + 4);
                    uint8_t b4 = b[j4];
                    uint32_t b4_val = ((uint32_t)b4 % 128);
                    if (b4_val > 15) return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INL, .val = { .DR_Inl = (Data_Codec_Low_decode_error_c){ .code = (Data_Codec_Low_error_code_c){ .tag = DATA_CODEC_LOW_EC_OVERFLOW }, .pos = i } } };
                    else {
                      uint32_t v4 = (v3 + (b4_val * 268435456U));
                      return (Data_Codec_Low_decode_result_c){ .tag = DATA_CODEC_LOW_DR_INR, .val = { .DR_Inr = (Data_Codec_Low_decode_result_ok){ .n = 5, .value = v4 } } };
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

uint32_t Data_Codec_Low_encode_bytes(Data_Codec_Low_codec_t c, uint32_t v, uint8_t *b, uint32_t i) {
  if (c.tag == DATA_CODEC_LOW_CT_TOKEN) return Data_Codec_Low_encode_token(v, b, i);
  else if (c.tag == DATA_CODEC_LOW_CT_BYTEVAL) return Data_Codec_Low_encode_byteval(c.val.CT_ByteVal, b, i);
  else if (c.tag == DATA_CODEC_LOW_CT_UINT8) return Data_Codec_Low_encode_uint8(v, b, i);
  else if (c.tag == DATA_CODEC_LOW_CT_WORD16BE) return Data_Codec_Low_encode_word16be(v, b, i);
  else if (c.tag == DATA_CODEC_LOW_CT_WORD32BE) return Data_Codec_Low_encode_word32be(v, b, i);
  else if (c.tag == DATA_CODEC_LOW_CT_WORD16LE) return Data_Codec_Low_encode_word16le(v, b, i);
  else if (c.tag == DATA_CODEC_LOW_CT_WORD32LE) return Data_Codec_Low_encode_word32le(v, b, i);
  else return Data_Codec_Low_encode_varint(v, b, i);
}

Data_Codec_Low_decode_result_c Data_Codec_Low_decode_bytes(Data_Codec_Low_codec_t c, uint8_t *b, uint32_t i, uint32_t n) {
  if (c.tag == DATA_CODEC_LOW_CT_TOKEN) return Data_Codec_Low_decode_token(b, i, n);
  else if (c.tag == DATA_CODEC_LOW_CT_BYTEVAL) return Data_Codec_Low_decode_byteval(c.val.CT_ByteVal, b, i, n);
  else if (c.tag == DATA_CODEC_LOW_CT_UINT8) return Data_Codec_Low_decode_uint8(b, i, n);
  else if (c.tag == DATA_CODEC_LOW_CT_WORD16BE) return Data_Codec_Low_decode_word16be(b, i, n);
  else if (c.tag == DATA_CODEC_LOW_CT_WORD32BE) return Data_Codec_Low_decode_word32be(b, i, n);
  else if (c.tag == DATA_CODEC_LOW_CT_WORD16LE) return Data_Codec_Low_decode_word16le(b, i, n);
  else if (c.tag == DATA_CODEC_LOW_CT_WORD32LE) return Data_Codec_Low_decode_word32le(b, i, n);
  else return Data_Codec_Low_decode_varint(b, i, n);
}

FStar_Pervasives_Native_tuple2__uint32_decode_result_c Data_Codec_Low_lemma_low_roundtrip_token(uint32_t v, uint8_t *b, uint32_t i, uint32_t n) {
  (void)n;
  uint32_t m = Data_Codec_Low_encode_token(v, b, i);
  Data_Codec_Low_decode_result_c r = Data_Codec_Low_decode_token(b, i, m);
  return (FStar_Pervasives_Native_tuple2__uint32_decode_result_c){ ._1 = m, ._2 = r };
}

FStar_Pervasives_Native_tuple2__uint32_decode_result_c Data_Codec_Low_lemma_low_roundtrip_byteval(uint8_t x, uint8_t *b, uint32_t i, uint32_t n) {
  (void)n;
  uint32_t m = Data_Codec_Low_encode_byteval(x, b, i);
  Data_Codec_Low_decode_result_c r = Data_Codec_Low_decode_byteval(x, b, i, m);
  return (FStar_Pervasives_Native_tuple2__uint32_decode_result_c){ ._1 = m, ._2 = r };
}

FStar_Pervasives_Native_tuple2__uint32_decode_result_c Data_Codec_Low_lemma_low_roundtrip_uint8(uint32_t v, uint8_t *b, uint32_t i, uint32_t n) {
  (void)n;
  uint32_t m = Data_Codec_Low_encode_uint8(v, b, i);
  Data_Codec_Low_decode_result_c r = Data_Codec_Low_decode_uint8(b, i, m);
  return (FStar_Pervasives_Native_tuple2__uint32_decode_result_c){ ._1 = m, ._2 = r };
}

FStar_Pervasives_Native_tuple2__uint32_decode_result_c Data_Codec_Low_lemma_low_roundtrip_word16be(uint32_t v, uint8_t *b, uint32_t i, uint32_t n) {
  (void)n;
  uint32_t m = Data_Codec_Low_encode_word16be(v, b, i);
  Data_Codec_Low_decode_result_c r = Data_Codec_Low_decode_word16be(b, i, m);
  return (FStar_Pervasives_Native_tuple2__uint32_decode_result_c){ ._1 = m, ._2 = r };
}

FStar_Pervasives_Native_tuple2__uint32_decode_result_c Data_Codec_Low_lemma_low_roundtrip_word16le(uint32_t v, uint8_t *b, uint32_t i, uint32_t n) {
  (void)n;
  uint32_t m = Data_Codec_Low_encode_word16le(v, b, i);
  Data_Codec_Low_decode_result_c r = Data_Codec_Low_decode_word16le(b, i, m);
  return (FStar_Pervasives_Native_tuple2__uint32_decode_result_c){ ._1 = m, ._2 = r };
}

FStar_Pervasives_Native_tuple2__uint32_decode_result_c Data_Codec_Low_lemma_low_roundtrip_word32be(uint32_t v, uint8_t *b, uint32_t i, uint32_t n) {
  (void)n;
  uint32_t m = Data_Codec_Low_encode_word32be(v, b, i);
  Data_Codec_Low_decode_result_c r = Data_Codec_Low_decode_word32be(b, i, m);
  return (FStar_Pervasives_Native_tuple2__uint32_decode_result_c){ ._1 = m, ._2 = r };
}

FStar_Pervasives_Native_tuple2__uint32_decode_result_c Data_Codec_Low_lemma_low_roundtrip_word32le(uint32_t v, uint8_t *b, uint32_t i, uint32_t n) {
  (void)n;
  uint32_t m = Data_Codec_Low_encode_word32le(v, b, i);
  Data_Codec_Low_decode_result_c r = Data_Codec_Low_decode_word32le(b, i, m);
  return (FStar_Pervasives_Native_tuple2__uint32_decode_result_c){ ._1 = m, ._2 = r };
}

FStar_Pervasives_Native_tuple2__uint32_decode_result_c Data_Codec_Low_lemma_low_roundtrip_varint(uint32_t v, uint8_t *b, uint32_t i, uint32_t n) {
  (void)n;
  uint32_t m = Data_Codec_Low_encode_varint(v, b, i);
  Data_Codec_Low_decode_result_c r = Data_Codec_Low_decode_varint(b, i, m);
  return (FStar_Pervasives_Native_tuple2__uint32_decode_result_c){ ._1 = m, ._2 = r };
}

FStar_Pervasives_Native_tuple2__uint32_decode_result_c Data_Codec_Low_lemma_low_encode_decode_match(Data_Codec_Low_codec_t c, uint32_t v, uint8_t *b, uint32_t i, uint32_t n) {
  if (c.tag == DATA_CODEC_LOW_CT_TOKEN) return Data_Codec_Low_lemma_low_roundtrip_token(v, b, i, n);
  else if (c.tag == DATA_CODEC_LOW_CT_BYTEVAL) return Data_Codec_Low_lemma_low_roundtrip_byteval(c.val.CT_ByteVal, b, i, n);
  else if (c.tag == DATA_CODEC_LOW_CT_UINT8) return Data_Codec_Low_lemma_low_roundtrip_uint8(v, b, i, n);
  else if (c.tag == DATA_CODEC_LOW_CT_WORD16BE) return Data_Codec_Low_lemma_low_roundtrip_word16be(v, b, i, n);
  else if (c.tag == DATA_CODEC_LOW_CT_WORD32BE) return Data_Codec_Low_lemma_low_roundtrip_word32be(v, b, i, n);
  else if (c.tag == DATA_CODEC_LOW_CT_WORD16LE) return Data_Codec_Low_lemma_low_roundtrip_word16le(v, b, i, n);
  else if (c.tag == DATA_CODEC_LOW_CT_WORD32LE) return Data_Codec_Low_lemma_low_roundtrip_word32le(v, b, i, n);
  else return Data_Codec_Low_lemma_low_roundtrip_varint(v, b, i, n);
}


