/* Generated by F* Custard extraction. Do not edit. */
#ifndef __CUSTARD_H
#define __CUSTARD_H

#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct Data_Codec_Low_error_code_c_s Data_Codec_Low_error_code_c;
typedef struct Data_Codec_Low_decode_error_c_s Data_Codec_Low_decode_error_c;
typedef struct Data_Codec_Low_decode_result_ok_s Data_Codec_Low_decode_result_ok;
typedef struct Data_Codec_Low_decode_result_c_s Data_Codec_Low_decode_result_c;
typedef struct Data_Codec_Low_codec_t_s Data_Codec_Low_codec_t;
typedef struct FStar_Pervasives_Native_tuple2__uint32_decode_result_c_s FStar_Pervasives_Native_tuple2__uint32_decode_result_c;

enum Data_Codec_Low_error_code_c_tags {
  DATA_CODEC_LOW_EC_UNEXPECTEDENDOFINPUT,
  DATA_CODEC_LOW_EC_EXPECTEDBYTE,
  DATA_CODEC_LOW_EC_OVERFLOW
};
struct Data_Codec_Low_error_code_c_s {
  enum Data_Codec_Low_error_code_c_tags tag;
  union {
    uint8_t EC_ExpectedByte;
  } val;
};
struct Data_Codec_Low_decode_error_c_s {
  Data_Codec_Low_error_code_c code;
  uint32_t pos;
};
struct Data_Codec_Low_decode_result_ok_s {
  uint32_t n;
  uint32_t value;
};
enum Data_Codec_Low_decode_result_c_tags {
  DATA_CODEC_LOW_DR_INL,
  DATA_CODEC_LOW_DR_INR
};
struct Data_Codec_Low_decode_result_c_s {
  enum Data_Codec_Low_decode_result_c_tags tag;
  union {
    Data_Codec_Low_decode_error_c DR_Inl;
    Data_Codec_Low_decode_result_ok DR_Inr;
  } val;
};
enum Data_Codec_Low_codec_t_tags {
  DATA_CODEC_LOW_CT_TOKEN,
  DATA_CODEC_LOW_CT_BYTEVAL,
  DATA_CODEC_LOW_CT_UINT8,
  DATA_CODEC_LOW_CT_WORD16BE,
  DATA_CODEC_LOW_CT_WORD32BE,
  DATA_CODEC_LOW_CT_WORD16LE,
  DATA_CODEC_LOW_CT_WORD32LE,
  DATA_CODEC_LOW_CT_VARINT
};
struct Data_Codec_Low_codec_t_s {
  enum Data_Codec_Low_codec_t_tags tag;
  union {
    uint8_t CT_ByteVal;
  } val;
};
struct FStar_Pervasives_Native_tuple2__uint32_decode_result_c_s {
  uint32_t _1;
  Data_Codec_Low_decode_result_c _2;
};

uint32_t Data_Codec_Low_encode_token(uint32_t v, uint8_t *b, uint32_t i);
uint32_t Data_Codec_Low_encode_byteval(uint8_t x, uint8_t *b, uint32_t i);
uint32_t Data_Codec_Low_encode_uint8(uint32_t v, uint8_t *b, uint32_t i);
uint32_t Data_Codec_Low_encode_word16be(uint32_t v, uint8_t *b, uint32_t i);
uint32_t Data_Codec_Low_encode_word32be(uint32_t v, uint8_t *b, uint32_t i);
uint32_t Data_Codec_Low_encode_word16le(uint32_t v, uint8_t *b, uint32_t i);
uint32_t Data_Codec_Low_encode_word32le(uint32_t v, uint8_t *b, uint32_t i);
uint32_t Data_Codec_Low_encode_varint(uint32_t v, uint8_t *b, uint32_t i);
Data_Codec_Low_decode_result_c Data_Codec_Low_decode_token(uint8_t *b, uint32_t i, uint32_t n);
Data_Codec_Low_decode_result_c Data_Codec_Low_decode_byteval(uint8_t x, uint8_t *b, uint32_t i, uint32_t n);
Data_Codec_Low_decode_result_c Data_Codec_Low_decode_uint8(uint8_t *b, uint32_t i, uint32_t n);
Data_Codec_Low_decode_result_c Data_Codec_Low_decode_word16be(uint8_t *b, uint32_t i, uint32_t n);
Data_Codec_Low_decode_result_c Data_Codec_Low_decode_word32be(uint8_t *b, uint32_t i, uint32_t n);
Data_Codec_Low_decode_result_c Data_Codec_Low_decode_word16le(uint8_t *b, uint32_t i, uint32_t n);
Data_Codec_Low_decode_result_c Data_Codec_Low_decode_word32le(uint8_t *b, uint32_t i, uint32_t n);
Data_Codec_Low_decode_result_c Data_Codec_Low_decode_varint(uint8_t *b, uint32_t i, uint32_t n);
uint32_t Data_Codec_Low_encode_bytes(Data_Codec_Low_codec_t c, uint32_t v, uint8_t *b, uint32_t i);
Data_Codec_Low_decode_result_c Data_Codec_Low_decode_bytes(Data_Codec_Low_codec_t c, uint8_t *b, uint32_t i, uint32_t n);
FStar_Pervasives_Native_tuple2__uint32_decode_result_c Data_Codec_Low_lemma_low_roundtrip_token(uint32_t v, uint8_t *b, uint32_t i, uint32_t n);
FStar_Pervasives_Native_tuple2__uint32_decode_result_c Data_Codec_Low_lemma_low_roundtrip_byteval(uint8_t x, uint8_t *b, uint32_t i, uint32_t n);
FStar_Pervasives_Native_tuple2__uint32_decode_result_c Data_Codec_Low_lemma_low_roundtrip_uint8(uint32_t v, uint8_t *b, uint32_t i, uint32_t n);
FStar_Pervasives_Native_tuple2__uint32_decode_result_c Data_Codec_Low_lemma_low_roundtrip_word16be(uint32_t v, uint8_t *b, uint32_t i, uint32_t n);
FStar_Pervasives_Native_tuple2__uint32_decode_result_c Data_Codec_Low_lemma_low_roundtrip_word16le(uint32_t v, uint8_t *b, uint32_t i, uint32_t n);
FStar_Pervasives_Native_tuple2__uint32_decode_result_c Data_Codec_Low_lemma_low_roundtrip_word32be(uint32_t v, uint8_t *b, uint32_t i, uint32_t n);
FStar_Pervasives_Native_tuple2__uint32_decode_result_c Data_Codec_Low_lemma_low_roundtrip_word32le(uint32_t v, uint8_t *b, uint32_t i, uint32_t n);
FStar_Pervasives_Native_tuple2__uint32_decode_result_c Data_Codec_Low_lemma_low_roundtrip_varint(uint32_t v, uint8_t *b, uint32_t i, uint32_t n);
FStar_Pervasives_Native_tuple2__uint32_decode_result_c Data_Codec_Low_lemma_low_encode_decode_match(Data_Codec_Low_codec_t c, uint32_t v, uint8_t *b, uint32_t i, uint32_t n);


#ifdef __cplusplus
}
#endif
#endif

